# Deployment script

- block:
  - name: Creating the deployment script
    template:
      src: bamboo_deployment.sh.j2
      dest: "{{ django_deployment_root_folder }}/{{ url }}/deployment.sh"
      mode: 0500
      owner: "{{ django_deployment_user }}"

  - name: Creating the secrets files
    template:
      src: secrets.py.j2
      dest: "{{ django_deployment_root_folder }}/{{ url }}/secrets.py"
      mode: 0400
      owner: "{{ django_deployment_user }}"

  - name: Sets additional permissions for the secrets file using ACLs
    acl:
      path: "{{ django_deployment_root_folder }}/{{ url }}/secrets.py"
      entity: "{{ uwsgi_user }}"
      etype: user
      permissions: "r"
      state: present
    when: use_acl

  - name: Sets additional permissions for the secrets file using groups
    file:
      path: "{{ django_deployment_root_folder }}/{{ url }}/secrets.py"
      mode: 0440
      group: "{{ uwsgi_group }}"
    when: not use_acl

  rescue:
    - debug:
        msg: "Error caught, please remove {{ django_deployment_root_folder }}/{{ url }} if needed"
    - command: /bin/false
