
# deployment script
- block:
  - name: Creating the deployment script
    template:
      src: bamboo_deployment.sh.j2
      dest: "{{ django_deployment_root_folder }}/{{ url }}/deployment.sh"
      mode: 0500
      owner: "{{ django_deployment_user }}"

  - name: Creating the secrets files
    template:
      src: secrets.py.j2
      dest: "{{ django_deployment_root_folder }}/{{ url }}/secrets.py"
      mode: 0400
      owner: "{{ django_deployment_user }}"

  - name: Sets additional permissions for the secrets file
    acl: 
      path: "{{ item }}" 
      entity: "{{ uwsgi_user }}" 
      etype: user 
      permissions: "r" 
      state: present
    with_items:
      - "{{ django_deployment_root_folder }}/{{ url }}/secrets.py"
      
  rescue:
    - debug: 
        msg: "Error caught, please remove {{ django_deployment_root_folder }}/{{ url }} if needed"
    # removes the whole directory in case of failure
    # Raffi: too dangerous in case there is already stuff in those folders (already deployed applications)
    #- file: path="{{ django_deployment_root_folder }}/{{ url }}" state=absent
    - command: /bin/false
