---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  
- name: restart apache2
  service: name=apache2 state=restarted enabled=yes

- name: restart uwsgi
  service: name=uwsgi state=restarted enabled=yes